import type { Metadata } from "next";
import { Bebas_Neue, Geist, Geist_Mono, Josefin_Sans, Roboto, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import ClientAOSProvider from '@/components/ClientAOSProvider';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const globalFont = Source_Code_Pro({
  subsets: ["latin"],
  weight: '400'
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${globalFont.className} antialiased bg-drafting`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
        <ClientAOSProvider />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
